// Auto-generated by AddressablesMappingGenerator. DO NOT EDIT.
namespace Generated.Addressables
{
    public enum AddressablesAssetName
    {
        Cube1,
        Cube2,
        Cube3,
        Level1
    }
}
