#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using Generated.Addressables;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;
using UnityEngine.AddressableAssets;

public static class AddressablesMappingGenerator
{
    private const string AssetPath = "Assets/Resources/AddressablesData/AddressablesGroupMapping.asset";
    private const string GroupEnumPath = "Assets/Project/Codebase/Extentions/Addressables/AddressablesGroup.cs";
    private const string AssetNameEnumPath = "Assets/Project/Codebase/Extentions/Addressables/AddressablesAssetName.cs";

    private static readonly FieldInfo EntriesField = typeof(AddressablesGroupMapping)
        .GetField("m_Entries", BindingFlags.Instance | BindingFlags.NonPublic);

    private struct AssetData
    {
        public string address;
        public string guid;
        public string groupName;
    }

    [MenuItem("Tools/Addressables/Generate Group Mapping")]
    public static void GenerateMapping()
    {
        var settings = AddressableAssetSettingsDefaultObject.Settings;
        if (settings == null)
        {
            Debug.LogError("Addressables settings not found!");
            return;
        }

        var groups = settings.groups
            .Where(g => g != null && !string.IsNullOrEmpty(g.Name))
            .OrderBy(g => g.Name)
            .ToArray();

        var sanitizedGroupNames = groups
            .Select(g => SanitizeName(g.Name))
            .Distinct()
            .OrderBy(n => n)
            .ToArray();

        var allAssets = groups
            .SelectMany(g => (g.entries ?? Enumerable.Empty<AddressableAssetEntry>())
                .Where(e => e != null)
                .Select(e => new AssetData
                {
                    address = !string.IsNullOrEmpty(e.address) ? e.address : e.guid,
                    guid = e.guid,
                    groupName = SanitizeName(g.Name),
                }))
            .ToArray();

        var (sortedAssetNames, addressToUniqueName) = GenerateUniqueAssetNames(allAssets);

        EnsureDirectoryExists(AssetPath);

        AssetDatabase.StartAssetEditing();
        try
        {
            WriteGroupEnumFile(sanitizedGroupNames);
            WriteAssetNameEnumFile(sortedAssetNames);
            CreateMappingAsset(allAssets, addressToUniqueName, sanitizedGroupNames, sortedAssetNames);
        }
        finally
        {
            AssetDatabase.StopAssetEditing();
        }

        AssetDatabase.Refresh();
        Debug.Log($"Generated AddressablesGroupMapping: {sanitizedGroupNames.Length} groups, {sortedAssetNames.Length} assets");
    }

    private static (string[] sortedNames, Dictionary<string, string> addressToName) GenerateUniqueAssetNames(AssetData[] assets)
    {
        var usedNames = new HashSet<string>();
        var addressToName = new Dictionary<string, string>();

        foreach (var asset in assets)
        {
            var sanitized = SanitizeName(asset.address);
            var uniqueName = sanitized;
            int counter = 1;
            while (!usedNames.Add(uniqueName))
                uniqueName = $"{sanitized}_{counter++}";

            addressToName[asset.address] = uniqueName;
        }

        return (usedNames.OrderBy(n => n).ToArray(), addressToName);
    }

    private static void WriteGroupEnumFile(string[] names)
    {
        var code = "// Auto-generated by AddressablesMappingGenerator. DO NOT EDIT.\n";
        code += "namespace Generated.Addressables\n{\n    public enum AddressablesGroup\n    {\n";
        code += string.Join(",\n", names.Select(n => $"        {n}"));
        code += "\n    }\n}\n";
        File.WriteAllText(GroupEnumPath, code);
    }

    private static void WriteAssetNameEnumFile(string[] names)
    {
        var code = "// Auto-generated by AddressablesMappingGenerator. DO NOT EDIT.\n";
        code += "namespace Generated.Addressables\n{\n    public enum AddressablesAssetName\n    {\n";
        code += string.Join(",\n", names.Select(n => $"        {n}"));
        code += "\n    }\n}\n";
        File.WriteAllText(AssetNameEnumPath, code);
    }

    private static void CreateMappingAsset(
        AssetData[] allAssets,
        Dictionary<string, string> addressToUniqueName,
        string[] groupNames,
        string[] assetNames)
    {
        var mapping = AssetDatabase.LoadAssetAtPath<AddressablesGroupMapping>(AssetPath);
        if (mapping == null)
        {
            mapping = ScriptableObject.CreateInstance<AddressablesGroupMapping>();
            AssetDatabase.CreateAsset(mapping, AssetPath);
        }

        var dict = new Dictionary<AddressablesAssetName, AddressablesGroupEntry>();

        foreach (var asset in allAssets)
        {
            if (!addressToUniqueName.TryGetValue(asset.address, out var uniqueName))
                continue;

            var assetNameIndex = Array.IndexOf(assetNames, uniqueName);
            if (assetNameIndex < 0)
                continue;

            var groupIndex = Array.IndexOf(groupNames, asset.groupName);
            if (groupIndex < 0)
                continue;

            var entry = new AddressablesGroupEntry
            {
                addressableGroup = (AddressablesGroup)(object)groupIndex,
                assetReference = new AssetReference(asset.guid),
            };

            dict[(AddressablesAssetName)(object)assetNameIndex] = entry;
        }

        EntriesField.SetValue(mapping, dict);
        EditorUtility.SetDirty(mapping);
        AssetDatabase.SaveAssets();
    }

    private static void EnsureDirectoryExists(string filePath)
    {
        var dir = Path.GetDirectoryName(filePath);
        if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            Directory.CreateDirectory(dir);
    }

    private static string SanitizeName(string name)
    {
        var sanitized = new string(name.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
        if (sanitized.Length > 0 && char.IsDigit(sanitized[0]))
            sanitized = "_" + sanitized;
        return string.IsNullOrEmpty(sanitized) ? "Unknown" : sanitized;
    }
}
#endif
